# see https://s.apache.org/asfyaml
github:
  description: "Apache Maven site"
  homepage: https://maven.apache.org/
  labels:
    - apache
    - maven
  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: true
  autolink_jira:
    - MNG
    - MNGSITE
    - MSITE
    - MINSTALL
    - MPIR
    - MANTTASKS
    - MGPG
    - SUREFIRE
    - MENFORCER
    - DOXIASITETOOLS
    - MPLUGIN
    - MWRAPPER
    - MSHARED
    - MSKINS
    - MPOM
    - ARCHETYPE
    - ARCHETYPES
    - INFRA
    - MASSEMBLY
    - FELIX
    - MRELEASE
notifications:
  commits: commits@maven.apache.org
  issues: issues@maven.apache.org
  pullrequests: issues@maven.apache.org
  jira_options: link label comment
