# see https://s.apache.org/asfyaml
github:
  description: "Apache Maven site"
  homepage: https://maven.apache.org/
  labels:
    - apache
    - maven
  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: true
  autolink_jira:
    - MNG
    - MNGSITE
    - MSITE
    - MINSTALL
    - MPIR
    - MANTTASKS
    - MGPG
    - SUREFIRE
    - MENFORCER
    - DOXIASITETOOLS
    - MPLUGIN
    - MWRAPPER
    - MSHARED
    - MSKINS
    - MPOM
    - ARCHETYPE
    - ARCHETYPES
    - INFRA
    - MASSEMBLY
    - FELIX
    - MRELEASE
  protected_branches:
    master: {}
    master-test:
      required_status_checks:
        # strict means "Require branches to be up to date before merging".
        strict: false
        # contexts are the names of checks that must pass.
        contexts:
          - 'Verify Site/Verify and build Maven Site'
  pull_requests:
    del_branch_on_merge: true
  features:
    issues: true

notifications:
  commits: commits@maven.apache.org
  issues: issues@maven.apache.org
  pullrequests: issues@maven.apache.org
