/'
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
'/
@startuml

<style>
    rectangle {
        BackgroundColor LightBlue
    }
}
</style>

package Misc {
  rectangle Archetypes
  rectangle "Distribution Tool Plugin"
  rectangle Indexer
  package Jenkins {
    rectangle Environment
    rectangle "Shared Libraries"
  }
  rectangle "Plugin Testing"
  package POM {
    rectangle "Apache"
    rectangle "Apache Resoures"
    rectangle "Maven"
  }
  package Skins {
    rectangle Fluido
  }
  rectangle Studies
  rectangle Wagon
}

'hidden dependencies to change layout
Archetypes -[hidden]> "Distribution Tool Plugin"
"Distribution Tool Plugin" -[hidden]> Indexer
Indexer -[hidden]> "Plugin Testing"
"Plugin Testing" -[hidden]> Studies
Studies -[hidden]> Wagon

Environment -[hidden]down-> "Shared Libraries"

"Apache" -[hidden]down-> "Apache Resoures"
"Apache Resoures" -[hidden]down-> "Maven"
"Apache" -[hidden]> Fluido

Archetypes -[hidden]down-> Environment
Indexer -[hidden]down-> "Apache"
"Plugin Testing" -[hidden]down-> Fluido

url of "Archetypes" is [[https://github.com/apache/maven-archetype]]
url of "Distribution Tool Plugin" is [[https://github.com/apache/maven-dist-tool]]
url of Indexer is [[https://github.com/apache/maven-indexer]]

url of Environment is [[https://github.com/apache/maven-jenkins-env]]
url of "Shared Libraries" is [[https://github.com/apache/maven-jenkins-lib]]

url of "Plugin Testing" is [[https://github.com/apache/maven-plugin-testing]]

url of "Apache" is [[https://github.com/apache/maven-apache-parent]]
url of "Apache Resoures" is [[https://github.com/apache/maven-apache-resources]]
url of "Maven" is [[https://github.com/apache/maven-parent]]

url of Fluido is [[https://github.com/apache/maven-fluido-skin]]

url of Studies is [[https://github.com/apache/maven-studies]]
url of Wagon is [[https://github.com/apache/maven-wagon]]

@enduml
