/*
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
*/
@startuml
!pragma layout smetana

<style>
    rectangle {
        BackgroundColor LightBlue
    }
}
</style>

package Misc {
  rectangle Archetypes
  rectangle Poms
  rectangle Skins
  rectangle Studies
  rectangle Indexer
  rectangle Wagon
  rectangle "Plugin testing"
  rectangle "dist-tool"
  package Jenkins {
    rectangle env
    rectangle lib
  }
}

'hidden dependencies to change layout
Archetypes -[hidden]right-> Poms
Poms -[hidden]right-> Skins
Skins -[hidden]right-> Studies
Studies -[hidden]right-> Indexer
Indexer -[hidden]right-> Wagon
Wagon -[hidden]right-> "Plugin testing"

Archetypes -[hidden]down-> "dist-tool"
"dist-tool" -[hidden]right-> Jenkins

url of "Archetypes" is [[https://github.com/apache/maven-archetype]]
url of Poms is [[https://github.com/apache/maven-parent]]
url of Skins is [[https://github.com/apache/maven-skins]]
url of Studies is [[https://github.com/apache/maven-studies]]
url of Indexer is [[https://github.com/apache/maven-indexer]]
url of Wagon is [[hhttps://github.com/apache/maven-wagon]]
url of "Plugin testing" is [[https://github.com/apache/maven-plugin-testing]]
url of "dist-tool" is [[https://github.com/apache/maven-dist-tool]]
url of env is [[https://github.com/apache/maven-jenkins-env]]
url of lib is [[https://github.com/apache/maven-jenkins-lib]]

@enduml
