/'
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.  
'/
@startuml
Platform o-- Bootstrap
Bootstrap  "1" o-- "many" BuildExtension
API "1" o-- "many" BuildExtension
CoreExtension "many" o-- "1" API

class Bootstrap {
 Plexus Classworlds
}

class CoreExtension {
 all packages defined in "/META-INF/maven/extension.xml"
}

class Platform {
 all JRE classes
}

class BuildExtension {
 dependencies
 classes
}

note right of API : Just composition of all Core Extensions
note right of Bootstrap : ${maven.home}/boot
note right of BuildExtension : Per GAV of plugin loaded with <extensions>true</extensions> or build extension
@enduml
